<<<<<<< Updated upstream
import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
=======

import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.*;
import java.sql.*;
import javax.swing.table.*;

public class Dashboard extends javax.swing.JFrame implements ActionListener {
>>>>>>> Stashed changes

public class Dashboard extends javax.swing.JFrame implements ActionListener{
    public String user;
<<<<<<< Updated upstream
=======
    public String selectUsername;
    public String selectPassword;
    StringSelection stringSelection;
    Clipboard clipboard;

>>>>>>> Stashed changes
    /**
     * Creates new form Dashboard
     */
    public Dashboard(String username) {
        user = username;
        System.out.print(user);
        initComponents();
        loadData();
        actionEvent();
    }
<<<<<<< Updated upstream
    
    public void loadData(){
=======

    public Dashboard() {
    }

    public void loadData() {
>>>>>>> Stashed changes
        this.userLabel.setText("Hello, " + user);
    }
    
    public void actionEvent() {
        addItem.addActionListener(this);
<<<<<<< Updated upstream
=======
        refreshBtn.addActionListener(this);
        copyPasswordBtn.addActionListener(this);
        copyUsernameBtn.addActionListener(this);
        deleteBtn.addActionListener(this);
>>>>>>> Stashed changes
//        signinBtn.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e){
        if (e.getSource() == addItem){
            CreateEntry ce = new CreateEntry();
            ce.show();
        }
<<<<<<< Updated upstream
    }
    
    
=======
        if (e.getSource() == refreshBtn) {
            DefaultTableModel model = (DefaultTableModel) entryTable.getModel();
            model.setRowCount(0);
            refreshData();
        }
        if (e.getSource() == copyPasswordBtn) {
            stringSelection = new StringSelection(selectPassword);
            clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, null);
        }
        if (e.getSource() == copyUsernameBtn) {
            stringSelection = new StringSelection(selectUsername);
            clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, null);
        }
        if (e.getSource() == refreshBtn) {

        }
    }

    public void refreshData() {
        try {
            Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/mprdb", "root",
                    "ninadsql");
            Statement st = connection.createStatement();
            String query = "select webName, webUsername, webPassword from " + user + ";";
            ResultSet rs = st.executeQuery(query);
            ResultSetMetaData rsmd = rs.getMetaData();
            DefaultTableModel model = (DefaultTableModel) entryTable.getModel();
            /* int cols = rsmd.getColumnCount();
            String [] colName = new String[cols];
            for(int i=0; i<cols; i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            model.setColumnIdentifiers(colName); */
            while (rs.next()) {
                String[] row = {rs.getString(1), rs.getString(2), rs.getString(3)};
                model.addRow(row);
//                model.getColumn
            }
        } catch (SQLException e1) {
            e1.printStackTrace();
        }
    }

>>>>>>> Stashed changes
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addItem = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();
<<<<<<< Updated upstream

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

=======
        jScrollPane2 = new javax.swing.JScrollPane();
        entryTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        copyUsernameBtn = new javax.swing.JButton();
        copyPasswordBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        jButton2.setText("Copy username");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Inter", 0, 18)); // NOI18N

        addItem.setBackground(new java.awt.Color(38, 127, 255));
        addItem.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        addItem.setForeground(new java.awt.Color(255, 255, 255));
>>>>>>> Stashed changes
        addItem.setText("Add Item");
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

<<<<<<< Updated upstream
=======
        userLabel.setBackground(new java.awt.Color(204, 255, 255));
        userLabel.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(51, 51, 51));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        entryTable.setBackground(new java.awt.Color(204, 204, 255));
        entryTable.setFont(new java.awt.Font("Inter", 0, 14)); // NOI18N
        entryTable.setForeground(new java.awt.Color(0, 0, 0));
        entryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Website Name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        entryTable.setGridColor(new java.awt.Color(204, 204, 255));
        entryTable.setRowHeight(30);
        entryTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        entryTable.setSelectionForeground(new java.awt.Color(51, 51, 51));
        entryTable.getTableHeader().setReorderingAllowed(false);
        entryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(entryTable);
        if (entryTable.getColumnModel().getColumnCount() > 0) {
            entryTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        refreshBtn.setBackground(new java.awt.Color(38, 127, 255));
        refreshBtn.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        copyUsernameBtn.setBackground(new java.awt.Color(38, 127, 255));
        copyUsernameBtn.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        copyUsernameBtn.setForeground(new java.awt.Color(255, 255, 255));
        copyUsernameBtn.setText("Copy Username");
        copyUsernameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyUsernameBtnActionPerformed(evt);
            }
        });

        copyPasswordBtn.setBackground(new java.awt.Color(38, 127, 255));
        copyPasswordBtn.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        copyPasswordBtn.setForeground(new java.awt.Color(255, 255, 255));
        copyPasswordBtn.setText("Copy Password");
        copyPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyPasswordBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(38, 127, 255));
        deleteBtn.setFont(new java.awt.Font("Inter", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

>>>>>>> Stashed changes
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< Updated upstream
                .addGap(208, 208, 208)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
=======
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(copyPasswordBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(copyUsernameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(refreshBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
>>>>>>> Stashed changes
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< Updated upstream
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
=======
                .addGap(26, 26, 26)
                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addItem, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(refreshBtn)
                                .addComponent(copyPasswordBtn)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(copyUsernameBtn)
                        .addComponent(deleteBtn)))
                .addGap(49, 49, 49))
>>>>>>> Stashed changes
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemActionPerformed

<<<<<<< Updated upstream
=======
    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void copyUsernameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyUsernameBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyUsernameBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void copyPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyPasswordBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_copyPasswordBtnActionPerformed

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void entryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entryTableMouseClicked
        int i = entryTable.getSelectedRow();
        TableModel model = entryTable.getModel();
        selectUsername = model.getValueAt(i, 1).toString();
        selectPassword = model.getValueAt(i, 2).toString();
    }//GEN-LAST:event_entryTableMouseClicked

>>>>>>> Stashed changes
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItem;
<<<<<<< Updated upstream
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
=======
    private javax.swing.JButton copyPasswordBtn;
    private javax.swing.JButton copyUsernameBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable entryTable;
    private javax.swing.JButton jButton2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
>>>>>>> Stashed changes
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}

